### ISSUE TITLE
Examples are not working properly

### ISSUE THREAD

**Issue by abhi-dev91** [argoproj-labs/hera#1011]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- No 

**2. This bug occurs in Hera when...**
- submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
When I am trying to run the example python workflows given in the example section of the hera, repository. I am getting a issue related to circular import, tried checking/changing hera version. But nothing worked out.

_Error log if applicable_:
```ImportError: cannot import name 'HTTPStatus' from partially initialized module 'http' (most likely due to a circular import) (/home/abhi/hera/examples/workflows/http.py)

Original exception was:
Traceback (most recent call last):
  File "/home/abhi/hera/examples/workflows/http.py", line 2, in <module>
    from hera.workflows import HTTP, Parameter, Workflow
  File "/home/abhi/.local/lib/python3.10/site-packages/hera/workflows/__init__.py", line 23, in <module>
    from hera.workflows.cluster_workflow_template import ClusterWorkflowTemplate
  File "/home/abhi/.local/lib/python3.10/site-packages/hera/workflows/cluster_workflow_template.py", line 2, in <module>
    from hera.exceptions import NotFound
  File "/home/abhi/.local/lib/python3.10/site-packages/hera/exceptions/__init__.py", line 7, in <module>
    from http import HTTPStatus
  File "/home/abhi/hera/examples/workflows/http.py", line 2, in <module>
    from hera.workflows import HTTP, Parameter, Workflow
ImportError: cannot import name 'HTTP' from partially initialized module 'hera.workflows' (most likely due to a circular import) (/home/abhi/.local/lib/python3.10/site-packages/hera/workflows/__init__.py)```
error: something broke!
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.expr import g
from hera.workflows import HTTP, Parameter, Workflow
from hera.shared import global_config
global_config.host = "cluster_endpoint/api/v1/namespaces/atmosly/services/argo-workflows-workflow-controller"
global_config.token = "bearer_token"



with Workflow(generate_name="http-") as w:
    HTTP(
        name="http",
        inputs=[Parameter(name="url")],
        timeout_seconds=20,
        url=f"{g.inputs.parameters.url:$}",
        method="GET",
        headers=[{"name": "x-header-name", "value": "test-value"}],
        success_condition=str(g.response.body.contains("google")),  # type: ignore
        body="test body",
    )

```

**Expected behavior**
The code should run and submit the workflow in the cluster or atleast give the issues related to k8s cluster.

**Environment**
- Hera Version: 5.14.3, 5.14.0
- Python Version: 3.10.6
- Argo Version: N/A

**Additional context**

**Comment by samj1912** [comment]
This seems to be happening because there is something wrong with your PYTHONPATH. I'm guessing you are executing this example named http.py via python -m http or that directory is in your PYTHONPATH for some reason. This is conflicting with the http module present in the stdlib. I recommend that you rename your example file to something like hera_http_example.py or make sure your PYTHONPATH is clean.
