### ISSUE TITLE
Allow `get_parameter` usage on `TemplateRef` steps/tasks

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#1013]
**Is your feature request related to a problem? Please describe.**
When using a template ref in a DAG/Steps, you cannot access its outputs via `get_parameter`, because Hera tries to confirm the parameter exists, which is not currently possible for TemplateRefs.

**Describe the solution you'd like**
Allow TemplateRefs to use `get_parameter` syntax without validation (for now).

**Describe alternatives you've considered**
Using the Argo templating syntax - `{{tasks.prev-step.outputs.parameters.param-name}}`

**Additional context**

**Comment by samj1912** [comment]
This is probably unneeded/stale with the new HEP.
