### ISSUE TITLE
Hera's token handling feels a bit awkward

### ISSUE THREAD

**Issue by ljyanesm** [argoproj-labs/hera#1016]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [ ] exporting to YAML
- [x] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_

When submitting a flow, the current way the token is provided feels a bit awkward based on the way the token 'comes' from the Argo UI.

For example, on version 3.5.5 the ArgoUI will provide a token in the shape of `ARGO_TOKEN="Bearer v2:<token>"`, which we are currently setting on the argo side by setting it as a parameter in `ArgoWorkflowsServerConfig`

```Python
ArgoWorkflowServerConfig(
        host=host, namespace=namespace, service_account_name=service_account_name, token=token
)
```

This is in turn used downstream by the `create_workflow` 
https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/service.py#L842 which contains on the Authorisation header a `Bearer ` prefix hardcoded.

The user needs to know about this quirk to understand that the value that needs to be set for the token is actually `v2:<token>` which seems unexpected.

_Error log if applicable_:

Receiving a 401 error code when submitting the workflow

**To Reproduce**
Full Hera code to reproduce the bug:
```py
import os
from hera.workflows import Workflow

with Workflow(name="my-workflow") as wf:
    pass

wf.workflows_service = ArgoWorkflowServerConfig(token=os.getenv("ARGO_TOKEN"))
wf.create()
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_
The above or equivalent should submit a workflow

**Environment**
- Hera Version: 5.14.2
- Python Version: 3.10.X
- Argo Version: 3.5.5

**Additional context**

**Comment by Adam-D-Lewis** [comment]
I'm also hitting this issue.  I want users to be able to run argo from the cli or from hera with an automatically set ARGO_WORKFLOW env var.  Currently, you have to tell the CLI user to append 'BEARER ' or else tell the hera user to strip 'Bearer ' before using ARGO_TOKEN.  I guess I could create a separat HERA_TOKEN, but it seems most natural for hera to expect the token exactly as Argo Workflows CLI expects it.

**Comment by flaviuvadan** [comment]
Thanks for reporting this @ljyanesm and @Adam-D-Lewis! See #1053
