### ISSUE TITLE
Dependabot commits making commit history noisy

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#1025]
Took a look at the commit history https://github.com/argoproj-labs/hera/commits/main/ but finding useful commits is quite hard with the number of commits from dependabot - @flaviuvadan do you know of any settings we could make use of to collect updates into fewer commits?

**Comment by flaviuvadan** [comment]
I agree. We can use [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)

**Comment by elliotgunton** [comment]
@flaviuvadan nice! The SemVer example makes sense for us to use I think - minors should be less frequent and we can review them individually, vs all these patches making the commit history noisy 👍 

>You can also specify grouping settings based on how updates affect a specific ecosystem and follow semantic versioning (SemVer). This means you can, for example, group all patch updates together. This approach helps Dependabot create as few pull requests as possible, while also reducing the chances of accidentally accepting changes that could cause issues. If a package follows SemVer, there's a higher chance (but not a guarantee) that minor and patch updates will be backwards compatible.
