### ISSUE TITLE
Runner IO (RunnerOutput) misbehaves for artifacts

### ISSUE THREAD

**Issue by sam2x** [argoproj-labs/hera#1030]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [x] No

**2. This bug occurs in Hera when...**
- [x] running on Argo with the Hera runner

<h2>Bug report</h2>

**Describe the bug**
The Hera RunnerOutput can't handle inherently file as artifact. Instead I have to read the content of the file myself and populate the returned value.  
   

**To Reproduce**
Full Hera code to reproduce the bug:
```py
class DefaultTaskInput(RunnerInput):
    file_path: Annotated[str, Parameter(name="file_path")] = "/tmp/rawdata.json"

class DefaultTaskOutput(RunnerOutput):
    data: Annotated[list, Artifact(name="xdata", archive=NoneArchiveStrategy())] = {}
    rawdata: Annotated[Path, Artifact(name="rawdata", archive=NoneArchiveStrategy(), path="/tmp/rawdata.json")] = ""

def my_func(my_input: Annotated[DefaultTaskInput, Parameter(name="my-input")]) -> DefaultTaskOutput:
       # i have a subprocess that run a command and save the execution to /tmp/rawdata.json"
       command = ["/test", "-o", my_input.file_path]  
       result = subprocess.run(command, input=None, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=text, check=True)
       stdout = result.stdout
       stderr = result.stderr
       otask = DefaultTaskOutput()
       otask.exit_code = 1
       otask.data = compile_xdata(my_input.file_path) 
       with open(my_input.file_path, 'r') as f:
         otask.rawdata = f.read()
       return otask
```

**Expected behavior**

I was expecting the following: 
1. "rawdata", with the file content of "/tmp/rawdata.json" without the need to open it myself and populate "rawdata" with its content since i provided "Path" in the Artifact definition. Here, if i remove the "with open(...) as f" block, the resulted content will be empty.    
2. "otask.data" (result of the processed rawdata), the output is well populated with the content, and show up as output,  however it doesnt show up as an "artifact" (cf picture below) despite being well recorded (also recorded inside my minio). I declared it as "artifact". Is this a normal behavior ? 
3. In DefaultTaskOutput, if i don't provide initial value to the declared variable, Pydantic will trigger an error. While in the documentation there are no initial value provided. I am a bit confused here (cf. doc: https://hera.readthedocs.io/en/stable/examples/workflows/experimental/script_runner_io/)
4. Is there an efficient/alternative way to avoid openning the files myself with Runner IO  (related to 1.) so I don't have to repeat the path both in the RunnerInput and RunnerOutput ?   
5. On the Hera best practice, from the snippet provided, should I replace "otask.data" to "otask.result" and/or add a "otask.result=stdout" ? And is it ok to override "exit_code" with my "subproceess" exit_code ? 
6. How can i dynamically generate a list of new artifact while inside the container execution flow ? E.g.: I don't know how many files will be generated ? Is this possible ? 

Thank you for your guidance. 

**Environment**
- Hera Version: 5.14.3
- Python Version: 3.11.8
- Argo Version: 3.5.2

**Additional context**
Based on the example of typical Artifact generation and RunnerOut: https://hera.readthedocs.io/en/stable/examples/workflows/artifacts/artifact/?h=archive#__tabbed_1_2
https://hera.readthedocs.io/en/stable/examples/workflows/experimental/script_runner_io/
![raw_data](https://github.com/argoproj-labs/hera/assets/11001928/a9bf29bb-d0c7-4749-b1f3-8d2046c75c53)

**Comment by sam2x** [comment]
Providing update on this: 
1. ok: I fixed it by adding explicit "Path" attribute and defining default value. Warning: the file somehow must have an extension...  
2. ok: The point 1 fixed it. 
3. ok: Assigned a default "path" value (same as the Path attribute string)
4. ok: Using the default assigned value of the RunningOutput variable works like charm.
5. ok: Not sure, but i assign the stdout by default and the returned subprocess code for exit code, and it works well.
6. ko - I haven't dig on this one yet.

**Comment by elliotgunton** [comment]
Nice job getting through those problems - we've been a bit busy to get round to this issue.

Re
> How can i dynamically generate a list of new artifact while inside the container execution flow ? 

This is not possible due to Argo's limitations - it needs to know how many artifacts to export from the pod.
