### ISSUE TITLE
Allowing extra information to Parameter/Artifact 

### ISSUE THREAD

**Issue by sam2x** [argoproj-labs/hera#1061]
**Is your feature request related to a problem? Please describe.**
I'm facing limitations with Parameter and Artifacts when used in the pydantic class (RunnerInput/RunnerOutput). 
In my application context, I want to add extra/metadata information to be used without breaking/modifying the Hera's source code.    

**Describe the solution you'd like**
I want to suggest the use of an extra field (named for example "metadata") within Parameter/Artifact, so from "user's  code" standpoint I could store any metadata within it.  Example : 
```
my_param : Annotated[str, Parameter(name="data", metadata=any_data_type)]
```
**Describe alternatives you've considered**
1. I have considered using decorator, but this raise an exception since Annotated "can't" be modified at runtime. 

```
def add_metadata(parameter, v =True):
    parameter.extra = v 
    return parameter
[...]
class BaseInput(RunnerInput):
    data: Annotated[str, add_metadata(Parameter(name="data"), True)]
```

2. I have considered using a dict, but afaik this could break the Hera's loader. 

```
class BaseInput(RunnerInput):
    data: Annotated[str, {"parameter": Parameter(name="data"), "extra": "extrainfo"}]
```
Any recommandations is welcome

**Comment by elliotgunton** [comment]
`Annotated` can take multiple metadata values - https://docs.python.org/3/library/typing.html#typing.Annotated

> Multiple metadata elements can be supplied (Annotated supports variadic arguments):

```py
@dataclass
class ctype:
    kind: str

Annotated[int, ValueRange(3, 10), ctype("char")]
```
> It is up to the tool consuming the annotations to decide whether the client is allowed to add multiple metadata elements to one annotation and how to merge those annotations.

Hera doesn't explicitly support multiple annotations at the moment (as we just check `get_args(annotation)[1]`), but it should work as long as `Parameter` or `Artifact` is the first piece of metadata according to code such as https://github.com/argoproj-labs/hera/blob/345e687315920f59cc7a4600a975e3cd026dedaa/src/hera/workflows/_runner/script_annotations_util.py#L154-L155

**Comment by elliotgunton** [comment]
Closing this as the immediate question has been answered - we can add a new issue to explicitly add multiple `Annotated` elements support if needed
