### ISSUE TITLE
Support user-provided certificates and keys

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#1079]
**Is your feature request related to a problem? Please describe.**
The `requests` package that Hera relies on to send requests to the Argo server supports specifying [client-provided certificates and keys](https://requests.readthedocs.io/en/latest/user/advanced/#client-side-certificates). This is very useful for specific user setups, such as having a proxy that intercepts a request and performs authentication not on the bearer token but on the certificate. 

**Describe the solution you'd like**
An API on the global config similar to the [token API](https://github.com/argoproj-labs/hera/blob/main/src/hera/shared/_global_config.py#L98) that allows either a string path to the certificate / key or a function to load that from a custom location (useful for when the cert is loaded dynamically from another location that needs auth on the user side). Maybe `cert` would be enough, and all it does is load a [tuple that's passed to requests like this](https://requests.readthedocs.io/en/latest/user/advanced/#client-side-certificates)

**Describe alternatives you've considered**
Could explore ways to intercept a requests package request but that feels like extra burden on the user and conflicts with Hera's ambition to support "configuring a platform" via hooks 

**Additional context**
None atm

**Comment by mrendi29** [comment]
@flaviuvadan  I will give this a try this week. First I'll open a PR that only covers the global config. Then I am thinking to also patch (separate PR) the [WorkflowService](https://github.com/argoproj-labs/hera/blob/c7e16dba11bfcf41491984e4de277e4a8a5a8acb/src/hera/workflows/service.py#L132) to include the cert 

What do you think?
