### ISSUE TITLE
Unable to set shareProcessNamespace Field in templates.

### ISSUE THREAD

**Issue by aland-mrsl** [argoproj-labs/hera#1144]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [x] exporting to YAML
- [x] submitting to Argo
- [x] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_

I don't see an api endpoint for setting the shareProcessNamespace field through Hera.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#podspec-v1-core

_Error log if applicable_:
```
error: something broke!
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import Workflow

with Workflow(name="my-workflow") as w:
    # Add your code here
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_

set shareProcessNamespace field as boolean true/false

**Environment**
- Hera Version: 5.16.0
- Python Version: 3.9.X
- Argo Version: 3.5.10

**Additional context**

**Comment by elliotgunton** [comment]
We have a pod spec example [here](https://hera.readthedocs.io/en/stable/examples/workflows/upstream/pod_spec_patch_wf_tmpl/?h=pod+spec) in the docs.
