### ISSUE TITLE
TemplateNameConflict error on hera==5.16.1

### ISSUE THREAD

**Issue by jeongukjae** [argoproj-labs/hera#1152]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [x] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_
Hera raises error when referencing script step in another step.

_Error log if applicable_:
```
Traceback (most recent call last):
  File "{SOME_PATH}/hera-5.16-name-conflict-error/script_containing_error.py", line 10, in <module>
    Step(name="hello-world", template=hello())
  File "{SOME_PATH}/hera-5.16-name-conflict-error/.venv/lib/python3.12/site-packages/pydantic/v1/main.py", line 349, in __init__
    __pydantic_self__._init_private_attributes()
  File "{SOME_PATH}/hera-5.16-name-conflict-error/.venv/lib/python3.12/site-packages/hera/shared/_global_config.py", line 181, in _init_private_attributes
    self.__hera_init__()
  File "{SOME_PATH}/hera-5.16-name-conflict-error/.venv/lib/python3.12/site-packages/hera/workflows/_context.py", line 30, in __hera_init__
    _context.add_sub_node(self)
  File "{SOME_PATH}/hera-5.16-name-conflict-error/.venv/lib/python3.12/site-packages/hera/workflows/_context.py", line 106, in add_sub_node
    raise TemplateNameConflict(f"Found multiple templates with the same name: {t.name}")
hera.workflows.exceptions.TemplateNameConflict: Found multiple templates with the same name: hello
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import Steps, script, Workflow, Step

@script()
def hello():
    print("hello")

with Workflow(name="hello-world-workflow") as wt:
    with Steps(name="main"):
        h = hello()
        Step(name="hello-world", template=h)

print(wt.to_yaml())
```

For more detailed, check https://github.com/jeongukjae/hera-5.16-name-conflict-error

**Expected behavior**
_A clear and concise description of what you expected to happen:_
Should produce following yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-workflow
spec:
  templates:
  - name: main
    steps:
    - - name: hello
        template: hello
    - - name: hello-world
        template: hello
  - name: hello
    script:
      command:
      - python
      image: python:3.8
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        print('hello')
```

**Environment**
- Hera Version: 5.16.1
- Python Version: 3.12.0
- Argo Version: Not needed

**Additional context**

The script runs as expected when following patch is applied:

```diff
 with Workflow(name="hello-world-workflow") as wt:
     with Steps(name="main"):
         h = hello()
-        Step(name="hello-world", template=h)
+        Step(name="hello-world", template=h.name)
 
 print(wt.to_yaml())
```

**Comment by elliotgunton** [comment]
This is an error in the Python code unrelated to the main issue which has already been resolved by #1153:

```py
    with Steps(name="main"):
        h = hello()
        Step(name="hello-world", template=h)
```

Where `h` is a `Step` object which you should not be setting on `template` which takes various template types (or a string)
