### ISSUE TITLE
Fields silently ignored in Pydantic I/O types

### ISSUE THREAD

**Issue by alicederyn** [argoproj-labs/hera#1190]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [X] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. I have searched for [existing issues](https://github.com/argoproj-labs/hera/issues)**
- [X] Yes

**3. This bug occurs in Hera when...**
- [X] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_

If a field on a pydantic Input/Output type has a Parameter annotation but the name is missing, the field is completely ignored.

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from typing import Annotated
from hera.workflows import Input, Parameter

class ExampleInput(Input):
    field1: str = "default"
    field2: Annotated[str, Parameter(description="second field")] = "another default"

parameters = ExampleInput()._get_as_arguments().parameters
assert len(parameters) == 2  # Error: field2 is missing
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_

Either `arguments` should contain two entries, with the second field defaulting to a name of `field2`, or validation should reject the class.

**Environment**
- Hera Version: 5.16.3
- Python Version: 3.11.8
- Argo Version: N/A

**Additional context**
It looks as if the code here is to blame: https://github.com/argoproj-labs/hera/blob/2eec4c282557823c661dae6b410b470d13a90be5/src/hera/workflows/io/_io_mixins.py#L149-L155

If name is missing, the field is skipped. Changing this to fall back to the field name would fix the issue.

**Comment by elliotgunton** [comment]
Related https://github.com/argoproj-labs/hera/issues/1165 - would be good to make name optional for Parameters/Artifacts together
