### ISSUE TITLE
Input/Output artifacts are not supported in dag

### ISSUE THREAD

**Issue by jeongukjae** [argoproj-labs/hera#1206]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. I have searched for [existing issues](https://github.com/argoproj-labs/hera/issues)**
- [x] Yes

**3. This bug occurs in Hera when...**
- [x] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
Argo workflow does not allow input/output artifact in dag.

https://github.com/argoproj/argo-workflows/blob/818fd90128f27daab5d35d8b1aa3afd9fee031e4/workflow/validate/validate.go#L629-L651

**To Reproduce**
https://github.com/argoproj-labs/hera/blob/main/examples/workflows/experimental/new_dag_decorator_artifacts.py

**Expected behavior**
Raise an erorr?

**Environment**
- Hera Version: 5.X.X
- Python Version: 3.X.X
- Argo Version: 3.X.X

**Additional context**

**Comment by elliotgunton** [comment]
Thanks Ukjae - I'm trying to keep most of the decorator bugs in #1162, so will close this as a duplicate. But thank you for confirming the code link! I think DAGs can take an Artifact but without a `path` set, so that the subtasks can use the Artifact. I am due to start working through the list of issues so will confirm.

**Comment by jeongukjae** [comment]
Nice! thanks Elliot!
