### ISSUE TITLE
We should error on Output field usage in DAG/Steps

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#1222]
> Output is not mandated but you can e.g. set result or exit_code on it which should probably be an error within a DAG/Steps function.

Originally from https://github.com/argoproj-labs/hera/issues/1162

**Comment by elliotgunton** [comment]
This may need something like https://github.com/pwwang/python-varname or https://github.com/alexmojaki/sorcery, or just a stack inspection mechanism to see if the function context is a dag/step-decorated function. We cannot simply check the `_context` is DAG or Steps, i.e.

```py
        if "result" in kwargs or "exit_code" in kwargs and isinstance(_context, (DAG, Steps)):
            raise SyntaxError("Cannot use `result` or `exit_code` in dag or steps decorator functions.")
```
in https://github.com/argoproj-labs/hera/blob/7b7a8c734815527e7a79f7e918ec0a33c2ec6514/src/hera/workflows/io/_io_mixins.py#L169-L174

As there will be script function calls where `Output(result="foo")` is valid, but the `_context` is still DAG/Steps.

Slightly more complex, so will leave out of #1221 and come back to this. Also it's more of an enhancement than a bug fix

**Comment by elliotgunton** [comment]
Actually, overcomplicating it for a basic fix - we can just check if `result` or `exit_code` are set in the object that the function return when constructing the dag, but we won't be able to raise an error on the line where the `result` or `exit_code` is set

**Comment by alicederyn** [comment]
We can have a separate validation flag in the context, and disable it temporarily in our script decorators?

**Comment by elliotgunton** [comment]
I don't think it's worth overcomplicating the codebase for now for a niche error case - the error text added in https://github.com/argoproj-labs/hera/commit/5b56891eb7bc27690bd756adc936c1edee9bc064 makes it obvious enough IMO
