### ISSUE TITLE
`Task.source` payloads should support `*args` and `**kwargs`

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#364]
@Trollgeir thoughts on this? I think `**kwargs` could be fairly easy to deal with, I wonder if `*args` is as easy as `**kwargs`

**Comment by elliotgunton** [comment]
I guess this transfers to `Script`'s `source` now - is it handled or even possible/desirable behaviour?
https://github.com/argoproj-labs/hera-workflows/blob/135ac6f7a6a77c3ac9d1b767e1f574b392979a7e/src/hera/workflows/script.py#L65

**Comment by flaviuvadan** [comment]
I know of several use cases where this would be valuable! I also think that it is possible to do this:
- accept args, kwargs in the source callable itself
- accept args, kwargs in the _callable_ template. This implies we have to add the kwargs for task/step and reserve the args, kwargs for the source
- upon a call the invoked callable makes sure that the types of args fit into source (serializable, etc) and iterate over the set kwargs to create independent Parameters with default values, as it does now for actual kwargs not **kwrags

**Comment by samj1912** [comment]
Closing in favor of #753
