### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#457]
I want to add some issue templates if that's fine by @flaviuvadan 🚀 

---

Issue templates should include:

- [x] Bug report: minimal Hera code to reproduce. Hera version and Argo version used.
- [x] Enhancement request: what and why? Optional "how".
- [x] Question (direct to Github discussions if preferred)

--- 
- [x] PR template should include:
* "Fixes #\<issue number>" [or] "Fixes \<description>"
* "tests added" tickbox
* "documentation added" tickbox
* "[Good commit messages](https://cbea.ms/git-commit/)" tickbox

Best to keep templates short and sweet ✨🍰✨

**Comment by flaviuvadan** [comment]
Leggo! 🚀
