### ISSUE TITLE
Mount the whole function inside a `Script` given a `source`

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#512]
At the moment only the body of a function is passed into the actual `Script` YAML spec, along with a prefix of parsed parameters and imports. It would be amazing if Hera would actually mount the whole function inside the script rather than just the body of the function. This will remove the need to avoid return statements, which is, at the moment, a bit awkward. A corollary of this is that Hera can automatically create outputs from the return type + result

**Comment by samj1912** [comment]
@flaviuvadan can this be closed now?

**Comment by flaviuvadan** [comment]
I think this will actually end up being a new script constructor. I can submit a different issue for that
