### ISSUE TITLE
Make `CallableTemplate` accept the kwargs of the function that is called with a `Script`'s `source`

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#513]
It would be amazing if Hera would support this syntax:
```python
@script(...)
foo(a, b, c):
    print(a, b, c)

with Workflow(...) as w:
    foo(a=1, b=2, c=3, name="testing")
```

For this to happen Hera needs to evaluate the `kwargs` passed to the `__call__` inside `CallableTemplate`, match them against a `source`, and create the necessary parameters.

**Comment by elliotgunton** [comment]
We can develop this feature on the [v5/infer-source-func-args branch](https://github.com/argoproj-labs/hera/tree/v5/infer-source-func-args)

**Comment by elliotgunton** [comment]
Closing for fresher issue #753 with more discussion
