### ISSUE TITLE
Add `apply_workflow_template` method

### ISSUE THREAD

**Issue by pbrunelle** [argoproj-labs/hera#520]
**Background**

To help perform live tests of workflow templates, we would like to be able to write the following in test cases:

```python
wflo_template = WorkflowTemplate(...)
wflo_template.apply(...)
wflo = wflo_template.run_as_worklow(...)
wflo.wait()
# Check post-conditions on workflow
```

**Proposal**

Add a method `apply_workflow_template` to `WorkflowsService` similar to existing methods `create_workflow_template` and `update_workflow_template` that creates a workflow template if it doesn't already exist, otherwise updates it.

Add a method `apply` to `WorkflowTemplate`, similar to existing method `create`.

**Comment by flaviuvadan** [comment]
Thank you for the submission @pbrunelle! Sounds like an awesome idea. Would you like to take a chance at it and submit a PR? :)
