### ISSUE TITLE
Add `run_as_workflow` method

### ISSUE THREAD

**Issue by pbrunelle** [argoproj-labs/hera#521]
**Background**

To help perform live tests of workflow templates, we would like to be able to write the following in test cases:

```python
wflo_template = WorkflowTemplate(...)
wflo_template.apply(...)
wflo = wflo_template.run_as_worklow(...)
wflo.wait()
# Check post-conditions on workflow
```

**Proposal**

Add a method `run_as_worklow` to `WorkflowTemplate` which takes the following parameters:
- `template`: the name of the template to run
- `inputs`: the list of inputs parameters

The method returns a `Workflow` object.

**Comment by flaviuvadan** [comment]
Will echo what I mentioned in #520! Very cool idea, especially in relationship to #520. Thoughts on opening a PR? :)
