### ISSUE TITLE
Add `wait` method to `Workflow`

### ISSUE THREAD

**Issue by pbrunelle** [argoproj-labs/hera#522]
**Background**

To help perform live tests of workflow templates, we would like to be able to write the following in test cases:

```python
wflo_template = WorkflowTemplate(...)
wflo_template.apply(...)
wflo = wflo_template.run_as_worklow(...)
wflo.wait()
# Check post-conditions on workflow
```

**Proposal**

Add a `wait` method to `Workflow` that returns only after the workflow has been completed, or a timeout has been reached.

**Comment by flaviuvadan** [comment]
One last round @pbrunelle - awesome idea! ❤️ Any chance you are open to submitting a PR?
