### ISSUE TITLE
Workflow submission fails with a validation error if `resources` are added to a `Container`

### ISSUE THREAD

**Issue by oginskis** [argoproj-labs/hera#547]
When defined a `hera.workflows.Container` as follows:
```
train_model = Container(
    name="train-model",
    image="xxx-train:latest",
    command=["sh", "-c"],
    args=["python  .."],
    inputs=[Artifact(name="dataset", path="/tmp/dataset/")],
    resources=Resources(
        cpu_request="5000m"
    ),
)
```
and added it as a `DAG` `Task` in the `Workflow` getting the following error on `workflow.create()`:

```
Traceback (most recent call last):
  File "...pipeline.py", line 45, in <module>
    w.create()
  File ".../.venv/lib/python3.11/site-packages/hera/workflows/workflow.py", line 334, in create
    return self.workflows_service.create_workflow(self.namespace, WorkflowCreateRequest(workflow=self.build()))
                                                                                                 ^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/hera/workflows/workflow.py", line 212, in build
    templates.append(template._build_template())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/hera/workflows/container.py", line 68, in _build_template
    return _ModelTemplate(
           ^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Template
resource -> action
  field required (type=value_error.missing)
```
Without the `resources` field on the `Container` the workflow is successfully submitted to Argo.

Python: `3.11`
Hera: `5.0.4` 
Argo: `3.4.5`

Is there anything I am doing wrong?

**Comment by flaviuvadan** [comment]
Hi @oginskis! Thanks for the issue submission :) This is a bug in Hera.. it's [this line](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/container.py#L90). The actual hardware resources, which you are requesting, are set correctly [here](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/container.py#L54) but they are incorrectly set on line 90, which wants a K8s resource definition, not a hardware resource definition. #548 fixes this
