### ISSUE TITLE
Script inline constructor is flakey

### ISSUE THREAD

**Issue by mshatkhin23** [argoproj-labs/hera#572]
Tried generating a script template with something like this:
```python
@script()
def echo(message: str) -> None:  # pragma: no cover
    """Prints out a message."""
    print(message)
```
and got something like this:
```yaml
source: "import os\nimport sys\nsys.path.append(os.getcwd())\nimport json\n\
        try: message = json.loads(r'''{{inputs.parameters.message}}''')\nexcept: message\
        \ = r'''{{inputs.parameters.message}}'''\n\ndef echo(message: str) -> None:\
        \  # pragma: no cover\n    \"\"\"Prints out a message.\"\"\"\n    # TODO Remove\
        \ function or replace with your logic\n    print(message)\n"
```

This seems to be because of the reliance on the function signature ending with a `:\n` string, from the code [here](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/script.py#L334).

**Comment by mshatkhin23** [comment]
@samj1912

**Comment by samj1912** [comment]
potential solution is to switch to one of https://stackoverflow.com/questions/38050649/getting-a-python-functions-source-code-without-the-definition-lines
