### ISSUE TITLE
Quick fix for `script_variations.py` example

### ISSUE THREAD

**Issue by ericdatakelly** [argoproj-labs/hera#585]
[`script_variations.py`](https://github.com/argoproj-labs/hera/blob/7f6bec0eb81449e6d47c0182f20608aeb7171841/examples/workflows/script_variations.py#LL1) results in an error and I think it's incomplete.  Here is a suggested fix.

- imports and implements `DAG`
- adds arguments for `multiline_function`
- adds print statements in `multiline_function`
- removes `print("Hello World!")` from `multiline_function`

```python
from hera.workflows import DAG, Workflow, script

@script()
def hello_world():  # pragma: no cover
    print("Hello World!")


@script()
def multiline_function(
    test: str,
    another_test: str,
) -> str:  # pragma: no cover
    print(test)
    print(another_test)

with Workflow(generate_name="fv-test-", entrypoint="d") as w:
    with DAG(name="d"):
        hello_world()
        multiline_function( 
            arguments={"test": "test string", "another_test": "another test string"}
            )
```

**Comment by flaviuvadan** [comment]
That is 100% correct @ericdatakelly, thank you for reporting it! 🚀  Any chance you are open to submitting a PR with the fix? :)

**Comment by ericdatakelly** [comment]
Thanks @flaviuvadan!  I'll submit a PR soon.
