### ISSUE TITLE
Cannot create artifacts in scripts without using "outputs=[Artifact(...)]" in @script decorator

### ISSUE THREAD

**Issue by abschm** [argoproj-labs/hera#591]
I've stumbled upon something that might be a bug or might be an intended change from Hera 4, but that is confusing to me.

In Hera 4, I was used to specifying artifacts inside `with Workflow as w:` with `task_name = Task("name", func, inputs=[...], outputs=[Artifact(...)],)`. 
When trying something similar in Hera 5 with `task_name = func(arguments=[...], outputs=[Artifact(...)],)`, no artifact is created and no error is printed. 
However, using `@script(outputs=[Artifact(...)],)` works as expected.

So this code works in Hera 5 and the artifact called "decorator_created_file" is created:
```
@script(
    outputs=[
        Artifact(
            name="decorator_created_file",
            path="/home/app/decorator_file.txt",
        )
    ],
)
def make_file_with_decorator():
    with open("decorator_file.txt", "w") as f:
        f.write("hello world!")


with Workflow(
    generate_name="script-artifact-output",
    entrypoint="dag",
) as w:
    with DAG(name="dag"):
        make_file_with_decorator_task = make_file_with_decorator()

    make_file_with_decorator_task
w.create()
```

But this code doesn't work in Hera 5 because the artifact called "no_decorator_created_file" is not created:
```
@script()
def make_file_without_decorator():
    with open("no_decorator_file.txt", "w") as f:
        f.write("hello world!")


with Workflow(
    generate_name="script-artifact-output",
    entrypoint="dag",
) as w:
    with DAG(name="dag"):
        make_file_without_decorator_task = make_file_without_decorator(
            outputs=[
                Artifact(
                    name="no_decorator_created_file",
                    path="/home/app/no_decorator_file.txt",
                )
            ],
        )

    make_file_without_decorator_task
w.create()
```

I tried tracking down the difference on my own but didn't find it.
Also, it would be really helpful to have an official example of script artifact passing.

**Comment by elliotgunton** [comment]
We already have a script artifact example: see [script_auto_infer.py](https://github.com/argoproj-labs/hera/blob/396c8cf2ec34ecd41f1f019ffe58829109bfb79a/examples/workflows/script_auto_infer.py) for a produce/consume artifact setup.

**Comment by elliotgunton** [comment]
Decided to add the example in the end as `script_auto_infer.py` is more of a bug check test (having the parameter as the same name as the artifact is not a usual scenario).
