### ISSUE TITLE
`AssertionError: workflow namespace not defined` was raised when running `Single step script` example

### ISSUE THREAD

**Issue by zhuwenxing** [argoproj-labs/hera#599]
```
from hera import Task, Workflow, WorkflowService


def say(m: str):
    print(m)


with Workflow('my-workflow', service=WorkflowService(host='my-argo-domain.com', token='my-argo-server-token')) as w:
    Task('say', say, func_params=[{'m': 'Hello, world!'}]) >> Task('say', say, func_params=[{'m': 'Goodbye, world!'}])

w.create()
```

In the previous example, we can access argo with host and token. So in 5.0 version, how can I know I was able to access argo?

I can use argo cli with my kubeconfig

![image](https://user-images.githubusercontent.com/12268675/234814997-6cf641f9-b8fa-4e3d-9b35-045fe489156e.png)

**Comment by tavallaie** [comment]
@zhuwenxing I just had [same problem ](https://github.com/argoproj-labs/hera/discussions/576#discussioncomment-5734592) .
Did you adding `http://` before your domain?
