### ISSUE TITLE
Add some lightweight host/namespace validation

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#603]
@flaviuvadan, I wanted to share a tip I learned the hard way when working with the requests library. In the following code:

```
resp = requests.post(
    url=urljoin(self.host, "api/v1/workflows/{namespace}").format(
        namespace=namespace if namespace is not None else self.namespace
    ),
    params=None,
    headers={"Authorization": f"Bearer {self.token}"},
    data=req.json(
        exclude_none=True, by_alias=True, skip_defaults=True, exclude_unset=True, exclude_defaults=True
    ),
    verify=self.verify_ssl,
)
```
If you don't include the protocol in the base URL, `urljoin` might not be able to determine the base URL properly, and only show the path part of the URL. For example, if you use `localhost:2746` instead of `https://localhost:2746`, you might only see `"api/v1/workflows/{namespace}" `and experience unexpected behavior.

To avoid this, make sure to include the protocol in the base URL, like so: `https://localhost:2746`. I hope this helps someone avoid the same issue I faced!"

_Originally posted by @tavallaie in https://github.com/argoproj-labs/hera/discussions/576#discussioncomment-5734592_

**Comment by flaviuvadan** [comment]
Thanks for bringing this up @elliotgunton. I certainly recognize the challenge.. should we add a validator to the global config or the service that checks for this? Perhaps the service is easiest because the init can have this check 🤔
