### ISSUE TITLE
Read Workflows from yaml

### ISSUE THREAD

**Issue by chaimt** [argoproj-labs/hera#609]
Currently the code supports writing hera classes to a yaml files:
workflow.to_yaml()

It would be very helpful to be able to read yaml files to hear classes.
This way we can have partial class definitions in yaml files, and then load it into the code

workflow.from_yaml(file)

container.from_yaml(file)

**Comment by elliotgunton** [comment]
As a halfway point, we do currently have pydantic's `parse_obj` to be able to work with the auto-generated models. i.e.

```py
from hera.workflows.models import Workflow
import yaml

with open("my-workflow.yaml", "r") as yaml_file:
    workflow = Workflow.parse_obj(yaml.safe_load(yaml_file.read())) # I'm sure there's a simpler way to do that...
```

So the goal of this issue would be to convert from the autogenerated pydantic models into Hera classes - maybe class functions like `parse_from_model` on compatible classes? Then `from_yaml` can convert to the model first (which also ensures the yaml is a valid model object for free) then convert to the Hera class
e.g.
```py
class Workflow(...):

    def parse_from_model(cls, w: _ModelWorkflow) -> Workflow:
        return Workflow(
            name=w.name,
            # do rest of 1-1 mapping here...
        )
        
```

**Comment by chaimt** [comment]
I think we would need some mixin that would enable to save and read each type of object
