### ISSUE TITLE
Add a v4 -> v5 migration guide

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#612]

**Comment by elliotgunton** [comment]
We haven't had any activity on this issue from users or questions in https://github.com/argoproj-labs/hera/discussions - wondering if we should close this issue as a "won't do" @flaviuvadan?

**Comment by flaviuvadan** [comment]
Yea, and it does not have upvotes.. let's close for now, and address questions 1 by 1 if they come up?
