### ISSUE TITLE
CronWorkflow complains about missing CronWorkflowStatus attributes

### ISSUE THREAD

**Issue by iameskild** [argoproj-labs/hera#636]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
When submitting a CronWorkflow to Argo, it complains that it is in violation of the Pydantic model. Upon closer inspection, it seems to be complaining specifically about the CronWorkflowStatus attributes (active, conditions, lastTimeScheduled). It was my understanding that these are not attributes that the user is responsible for setting. The CronWorkflow is still submitted and appears to run but the error message below is produced regardless.

_Error log if applicable_:
```
115, in create_cron_workflow
    w.create()
  File "/Users/eskild/miniconda3/envs/nebari/lib/python3.11/site-packages/hera/workflows/cron_workflow.py", line 82, in create
    return self.workflows_service.create_cron_workflow(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eskild/miniconda3/envs/nebari/lib/python3.11/site-packages/hera/workflows/service.py", line 395, in create_cron_workflow
    return CronWorkflow(**resp.json())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for CronWorkflow
status -> active
  none is not an allowed value (type=type_error.none.not_allowed)
status -> conditions
  none is not an allowed value (type=type_error.none.not_allowed)
status -> lastScheduledTime
  none is not an allowed value (type=type_error.none.not_allowed)
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import CrongWorkflow, DAG, script

@script()
def foo(a, b=42, c=None):
    print(a, b, c)

with CronWorkflow(
    generate_name="cron-test-",
    entrypoint="D",
    schedule="* * * * *",
    starting_deadline_seconds=0,
    concurrency_policy="Replace",
    successful_jobs_history_limit=4,
    failed_jobs_history_limit=4,
    cron_suspend=False,
) as w:
    with DAG(name="D"):
        foo(name="b-unset-c-unset", arguments={"a": 1})
        foo(name="b-set-c-unset", arguments={"a": 1, "b": 2})
        foo(name="b-unset-c-set", arguments={"a": 1, "c": 2})
        foo(name="b-set-c-set", arguments={"a": 1, "b": 2, "c": 3})

w.create()
```

**Expected behavior**
_A clear and concise description of what you expected to happen:_

**Environment**
 - OS: [e.g. iOS] MacOS
 - Browser: [e.g. chrome, safari] Chrome
 - Version of Hera: [e.g. 5.1.6, 4.4.2] `5.2.0`
 - Version of Argo: [e.g. 3.4.7] `3.4.4`

**Additional context**

**Comment by flaviuvadan** [comment]
Thanks for the bug report @iameskild! I can reproduce the bug using your example. Let me know if https://github.com/argoproj-labs/hera/pull/637 makes sense!
