### ISSUE TITLE
Add the ability to spin up a local minikube cluster for Hera to be tested on local by users

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#654]
**Is your feature request related to a problem? Please describe.**
Hera cannot really run "locally" at the moment, which likely makes it challenging for potential adopters to try our Hera _before_ committing/putting in a lot of work to spin up Argo Workflows

**Describe the solution you'd like**
Maybe a Hera CLI that spins up a local Argo Workflows cluster via minikube?

**Describe alternatives you've considered**
An alternative for now is to construct a local engine that can iterate over the tasks/scripts set in a Hera workflow and execute them locally, in Python. However, this only works for scripts. In addition, resolving artifacts might be problematic for users, as Hera does not know AOT what size the artifacts are, might not have auth to access them, etc.

**Additional context**
None atm

**Comment by elliotgunton** [comment]
Do you think we can call this fixed if we add some README/[quick start guide](https://hera.readthedocs.io/en/stable/walk-through/quick-start/) instructions to use `make install-k3d install-argo run-argo` using the repo itself in e.g. github codespaces? We can then revisit the CLI idea when we want to prioritise it

**Comment by flaviuvadan** [comment]
> Do you think we can call this fixed if we add some README/[quick start guide](https://hera.readthedocs.io/en/stable/walk-through/quick-start/) instructions to use make install-k3d install-argo run-argo using the repo itself in e.g. github codespaces? We can then revisit the CLI idea when we want to prioritise it

Yep, I think that works! Do we have to switch a few examples to use localhost:2746 too? Or maybe most of them will "just work"
