### ISSUE TITLE
Compatibility with pyyaml 5

### ISSUE THREAD

**Issue by GuyPozner** [argoproj-labs/hera#695]
**Is your feature request related to a problem?**

Hera conda package cannot be installed with awscli conda package in the same environment.

**How to reproduce?**

```bash
mamba create -n rep-hera -c conda-forge "hera>=5" awscli
```

**Describe the solution you'd like**

Remove the pyyaml version 6 constrained in poetry and [conda feedstock](https://github.com/conda-forge/hera-workflows-feedstock/blob/main/recipe/meta.yaml#L26).

**Comment by elliotgunton** [comment]
Closing due to lack of interest/response
