### ISSUE TITLE
BaseModel's Field definitions to use known-word argument instead of positional argument for default values

### ISSUE THREAD

**Issue by AndreLobato** [argoproj-labs/hera#699]
**Is your feature request related to a problem? Please describe.**

This is more a coding concern for whom uses VSCode (and maybe other IDEs as well) and are trying to benefit from Pylance's strict type validations. The issue is that Pylance fail to validate Models with default field values when they are defined as a positional argument of Field, for example:

![Screenshot from 2023-06-29 15-33-13](https://github.com/argoproj-labs/hera/assets/359120/f6448ca4-c2c0-42ed-b0bc-470d0242f3b3)

In the case of hera models this can be seen as:
 
![Screenshot from 2023-06-29 15-38-39](https://github.com/argoproj-labs/hera/assets/359120/f44ef20b-608c-4f1b-9c8f-a645570b5c20)

**Describe the solution you'd like**

The solution for this is rather simple, just need to declare the default value as known-word argument in the models such as...

![Screenshot from 2023-06-29 15-35-51](https://github.com/argoproj-labs/hera/assets/359120/1f55fc28-43f4-4592-a598-70c4b02a5173)

I understand the models are generated using datamodel-codegen and there's a flag called `--use-default-kwarg` which I believe will fix this issue

**Describe alternatives you've considered**

The alternative for the moment is to add a comment in the lines where this occur so type is ignored such as `#type: ignore` or `#pyright: ignore` but I wish to keep things clean and as much as possible respect types constrains throughout.

**Additional context**

This issue or similar were discussed in the pydantic repo as in:  pydantic/pydantic#3753 and pydantic/pydantic#3617

Some claim to be a bug, others that is a convoluted problem with the validation libraries... regardless, considering the issue has been closed for more than a year I suspect they are not changing any anytime soon.

**Comment by flaviuvadan** [comment]
Thanks for flagging this @AndreLobato! We certainly appreciate the dev ex concern. I will add the flag you suggested and regenerate the models
