### ISSUE TITLE
wait fails assertion due to race condition

### ISSUE THREAD

**Issue by sebpretzer** [argoproj-labs/hera#721]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
[Assertion](https://github.com/argoproj-labs/hera/blob/c7374e76e4ed07432f00d7bafeed8dd4c563b9f8/src/hera/workflows/workflow.py#L412) fails due to what I believe is a race condition with Argo starting the workflow. I am unclear if this is an issue with my OS and Argo cluster, or if this is a general bug. 

_Error log if applicable_:
```
AssertionError: workflow phase not defined for workflow status artifact_gc_status=None artifact_repository_ref=None compressed_nodes=None conditions=None estimated_duration=None finished_at=None message=None nodes=None offload_node_status_version=None outputs=None persistent_volume_claims=None phase=None progress=None resources_duration=None started_at=None stored_templates=None stored_workflow_template_spec=None synchronization=None
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import Steps, Workflow, script


@script()
def echo(message: str):
    print(message)


with Workflow(
    generate_name="single-script-",
    entrypoint="steps",
) as w:
    with Steps(name="steps"):
        echo(arguments={"message": "A"})

w.create()
w.wait() # offending line
```

**Expected behavior**
If I run the code below, then the script successfully waits for workflow completion. 
```py
w.create()
time.sleep(0.5) # added by me
w.wait() 
```

**Environment**
 - OS: Amazon Linux 2
 - Browser: N/A
 - Version of Hera: 5.5.2
 - Version of Argo: v3.4.8

**Additional context**

**Comment by flaviuvadan** [comment]
Thanks for the issue @sebpretzer! Any chance you can try `w.create(wait=True)`?

**Comment by flaviuvadan** [comment]
This is quite interesting because what you have is essentially what happens when one runs `w.create(wait=True, poll_internal=5)`:
- create the workflow
- call wait with 5 seconds poll interval
- sleep 5 seconds
- get

**Comment by sebpretzer** [comment]
The same assertion is thrown when I try `w.create(wait=True)`. I can confirm that it does work if I subclass workflow and add the same sleep before actually waiting. 

It is failing before the while loop even starts, so it cannot sleep for the poll interval duration before attempting to get.

**Comment by sebpretzer** [comment]
Thank you for the speedy fix!

**Comment by Pierre-Bartet** [comment]
Still randomly happening in `5.25.1`

**Comment by elliotgunton** [comment]
@Pierre-Bartet you might be hitting #1562 ?
