### ISSUE TITLE
validate_storage_units() for memory Resources has some issues

### ISSUE THREAD

**Issue by FullDataAlchemist** [argoproj-labs/hera#748]
hi, 

**This bug occurs when...**

```
Container(
            name="sample_name",
            image="python:3.10"
....
....
            resources=Resources(
                            cpu_limit="{{inputs.parameters.cpu_limit}}",
                            memory_limit="{{inputs.parameters.memory_request}}",
...
...

)
```

<h2>Bug report</h2>

**Describe the bug**
for the sample above, in defining Resources there is no problem with cpu_limit or cpu_request but for the memory_limit or memory_request, there is a validate_storage_util() method that validates the string using regex, and it's not correct.

this bug also, for this patterns are correct : 
                           `memory_limit="Gi{{inputs.parameters.memory_request}} whatever you want to type here!!",`

the problem comes from:
https://github.com/argoproj-labs/hera/blob/49140d07990cca8f2a22b72f1cf08aea8c225ca5/src/hera/workflows/validators.py#L66 

_Error log if applicable_:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Resources
__root__
  unsupported unit for parsed value {{inputs.parameters.memory_request}} (type=assertion_error)
```

**Expected behavior**
I want to pass an argument for memory limit and I have to send it like this : 
`memory_limit="{{inputs.parameters.memory_request}}",`

**Comment by flaviuvadan** [comment]
Hey @FullDataAlchemist! Thanks for the question. Those validators are there because K8s also implements similar/the same validation. If you pass `{{inputs.parameters.memory}}` in the resource field K8s will complain about it AFAIK. Instead, Argo provides pod spec patching that you can use to parameterize resources. Here's an example from [Hera docs](https://hera.readthedocs.io/en/stable/examples/workflows/upstream/pod_spec_patch_wf_tmpl/?h=pod+spec+patch):
```python
import json
from hera.workflows import Container, Parameter, Workflow

with Workflow(
    generate_name="pod-spec-patch-",
    entrypoint="whalesay",
    arguments=[Parameter(name="cpu-limit", value="100m")],
) as w:
    whalesay = Container(
        name="whalesay",
        image="docker/whalesay:latest",
        command=["cowsay"],
        args=["hello world"],
        pod_spec_patch=json.dump({"containers":[{"name":"main", "resources":{"limits":{"cpu": '
        '"{{workflow.parameters.cpu-limit}}" }}}]}),
    )
```
