### ISSUE TITLE
Callable syntax support

### ISSUE THREAD

**Issue by dejamiko** [argoproj-labs/hera#753]
## Status quo

Currently, passing arguments to scripts is rather inconvenient. The general idea is passing a list to an `arguments` keyword argument. There is a simplified “dictionary” style for passing in parameters without instantiating the `Parameter` objects:
```python
@script()
def echo_all(a_number, a_bool, a_string):
    print(a_number)
    print(a_bool)
    print(a_string)


with Workflow(generate_name="example-callable-", entrypoint="my_steps") as w:
    with Steps(name="my_steps") as s:
        echo_all(arguments={"a_number": 3, "a_bool": True, "a_string": "abc"})

        # Which is a simplified syntax of:
        Step(name="echo_all", source=echo_all, arguments={...})
```

The same cannot be said about `Artifacts` though. They necessitate the “list” syntax which requires instantiating all the objects on the way.

```python
@script()
def echo_all(an_int, a_bool, a_string, an_artifact: Annotated[str, Artifact(name="my-artifact", path="tmp/file", loader=ArtifactLoader.file)]):
    print(an_int)
    print(a_bool)
    print(a_string)
    print(an_artifact)


with Workflow(generate_name="example-callable-", entrypoint="my_steps") as w:
    with Steps(name="my_steps") as s:
        echo_all(
            arguments=[
                Parameter(name="an_int", value=1),
                Parameter(name="a_bool", value=True),
                Parameter(name="a_string", value="abc"),
                Artifact(name="my-artifact", from_="somewhere"),
            ]
        )
```
In either case, the way arguments are passed is through the arguments field of the script. What would be the most Pythonic way of writing this which would emphasise the one-to-one of a Python function and a Hera template?

## Design
It is relatively easy to implement a similar solution that allows for args and kwargs (#647). There is however a problem with some corner cases. They are rather convoluted, but for instance for:
```python
@script()
def person(age=42, name="Joe"):
   print(age, name)


with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
   with DAG(name="d"):
       person(name="Jane", name="my-argo-job") # <- we have a clash with name but we can't use positional syntax because we want to use age's default value
```

It’s not possible to use keyword arguments because of the clash with the Argo params. Positional arguments cannot be used in this case, since we want to use the default value of `age`. The user would have to resort to the old syntax:

```python
@script()
def person(age=42, name="Joe"):
   print(age, name)


with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
   with DAG(name="d"):
       person(arguments={"name": "Jane"}, name="my-argo-job") # <- we have a clash with name but we can't use positional syntax because we want to use age's default value
```

One solution is to first pass in all the arguments to the script function which returns a Task/Step, depending on the context. Then, a second method call updates the object to contain the Task/Step specific attributes.

```python
@script()
def person(age=42, name="Joe"):
   print(age, name)


with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
   with DAG(name="d"):
       person(name="Jane").with_(name="my-argo-job")
```

The `with_` method could be implemented as follows

```python
class Task:
    ...
    def with_atrributes(self, name: str, ...) -> Task:
        self.name = name
        ...
        return self 
```

Something similar to this can be used, possibly within a mixin to share that behaviour between `Task` and `Step`. 

I believe this approach is beneficial because it allows for passing in the arguments in a natural Pythonic way to the function and then setting the `Task`/`Step` attributes in one simple step. It allows for passing in a dictionary of arguments.

## How can we implement this alongside the old syntax?
We introduce this natural arguments passing as an experimental feature. To enable it, the user must use a kwarg in the script decorator 
```python
@script(directly_callable=True)
def echo_num(number: int = 42):
   print(number)


with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
   with DAG(name="d"):
       echo_num().with_(name="my-echo", with_params=[1, 2, 3])
```
Then, in `TemplateInvocatorSubNodeMixin`, the `__call__` function can be updated and include a check for `self.directly_callable`. This can also be set in e.g. `Containers` to allow for callable syntax for those. `directly_callable` could maybe be an attribute of the `TemplateInvocatorSubNodeMixin` to allow it to be used in any of the classes that use it. With this check done, we can take the args and kwargs and assume all of them are actually function arguments. We can populate `kwargs["arguments"]` with those and return depending on the context. We can most likely do without introducing new classes for those uses, since the only difference is introducing one method.

This approach allows the user to decide on a granular level if they want to use the old or the new syntax. Calls to scripts with old syntax can coexist with the new syntax within the same workflow and file. The decision can be made for each callable. 

If the community does not like this feature, it is easy to disable/remove. The previous way of passing arguments is continually supported. 

If the community likes the feature, we have a choice of how to handle that. 

1. We can try to support both syntaxes forever. To make it easier to use the new syntax, we can move the `directly_callable` setting to `global_config` which reduces repetition. In this scenario, there is no sudden breaking point and the users can migrate if they want to or use a mix of both features. The new one will get new features but both will be maintained. 
2. We can also decide that breaking changes are a part of life and flip the switch with one of major releases. We would change the default from `directly_callable=False` to `directly_callable=True` which would break code using the previous syntax. We can still support the old syntax with manual `directly_callable=False` if the users would like that.

## Examples
This syntax for some currently existing examples looks as follows:

```python
from hera.workflows import DAG, Workflow, script


@script(directly_callable=True)
def foo(a, b=42, c=None):
    print(a, b, c)


with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
    with DAG(name="d"):
        foo(1).with_(name="b-unset-c-unset")
        foo(1, 2).with_(name="b-set-c-unset")
        foo(1, c=2).with_(name="b-unset-c-set")
        foo(1, 2, 3).with_(name="b-set-c-set")
```

```python
from hera.workflows import Container, Steps, Workflow

with Workflow(generate_name="container-on-exit-", entrypoint="step-template") as w:
    exit_container = Container(
        name="exitContainer",
        image="docker/whalesay",
        command=["cowsay"],
        args=["goodbye world"],
    )
    whalesay = Container(
        name="whalesay", image="docker/whalesay", command=["cowsay"], args=["hello world"], directly_callable=True
    )
    with Steps(name="step-template"):
        whalesay().with_(name="stepA", on_exit=exit_container)
        whalesay().with_(name="stepB", on_exit=exit_container)
```

```python
"""
This example showcases how to generate and parallelize generated sequences
"""
from hera.workflows import DAG, Workflow, script
from hera.workflows.models import Sequence


@script(directly_callable=True)
def gen_num():
    print(3)


@script(directly_callable=True)
def say(message: str):
    print(message)


with Workflow(generate_name="with-sequence-example", entrypoint="d") as w:
    with DAG(name="d"):
        t1 = gen_num().with_(name="t1")
        t2 = say("{{item}}").with_(name="t2", with_sequence=Sequence(count=t1.result, start="0"))
        t3 = say("{{item}}").with_(
            name="t3",
            with_sequence=Sequence(start=t1.result, end="5", format="2020-05-%02X"),
        )
        t1 >> [t2, t3]
```

**Comment by samj1912** [comment]
There are a few issues I see with this.

1. Output types. What are the input/output types for each of these operations? Does `.name()`, `.with_sequence()` return back the modified object or self? does it do a deep copy or a shallow copy?
2. The `.name` attribute is currently a properly that returns a string for a task/step. We have now overloaded it. How do we distinguish between the property and the method now? In general I am not a big fan of methods with the same name as the attribute being callable this way. 
3. What happens to other properties of a step/task that the callable syntax clashes with?


I would like to see the types before and after each of these transformations and how we are planning to preserve the compatibility with the current code.

**Comment by samj1912** [comment]
If we still want to set something properties up in a callable fashion, I would rather see something like `with_*` methods like `with_name` etc to avoid clashes with properties or a collective with `with` method which takes in all the same arguments as the step class.

so something like

```
t1 = callable().with_name(name)
t2 = callable().with(name=name)
```

**Comment by dejamiko** [comment]
Those are some very good questions and suggestions. I believe in 2. we have a clashing problem. I assumed Python would distinguish based on the different number of parameters but it seems unable to do so. This is a big problem with this syntax. I really like the suggested `.with` syntax but unfortunately it is not allowed in Python since `with` is a keyword. Maybe we can use `with_attributes` to suggest to the user that those are the `Task`/`Step` attributes. I updated the issue description to contain the new design with the `with_attributes`.

**Comment by samj1912** [comment]
@dejamiko a common solution is to suffix python keywords with an underscore

So it will become `callable().with_()`

**Comment by dejamiko** [comment]
> @dejamiko a common solution is to suffix python keywords with an underscore
> 
> So it will become `callable().with_()`

Sure, I actually had that in the design doc but decided to go with `with_attributes` since it's more descriptive. If you prefer `with_` , we can use that instead

**Comment by elliotgunton** [comment]
A question came up today discussing with @dejamiko of whether we should support the callable syntax for all callable templates or just for script-decorated functions. My view is that we only have this callable syntax for decorated functions as it's the most transparently discoverable syntax for users, compared to creating a callable container, giving it inputs, then passing as if it's a function. Some of the examples above show this way:

```py
with Workflow(...):
    whalesay = Container(
        name="whalesay",
        inputs=[Parameter(name="message")],
        image="docker/whalesay",
        command=["cowsay"],
        args=["{{inputs.parameters.message}}"],
    )
    whalesay("test") # hmmm... Should it accept kwargs only?
    whalesay(message="test") # less hmmm? Maybe acceptable?
```

**Comment by flaviuvadan** [comment]
@elliotgunton if we do add it broadly to the callable template mixin then I think the second option makes more sense! Certainly less confusing to use kwargs in that case

**Comment by elliotgunton** [comment]
To get around the weird `with_param`/`with_item` syntax not taking args in the call, we could use a literal `for` loop syntax, where, if the template name is the same, it builds up the `with_param` value:

```py
@script(directly_callable=True)
def echo_num(number: int = 42):
   print(number)


with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
   with DAG(name="d"):
        for i in [1, 2, 3]:
           echo_num(i).with_(name="my-echo")
```

**Comment by dejamiko** [comment]
> To get around the weird `with_param`/`with_item` syntax not taking args in the call, we could use a literal `for` loop syntax, where, if the template name is the same, it builds up the `with_param` value:
> 
> ```python
> @script(directly_callable=True)
> def echo_num(number: int = 42):
>    print(number)
> 
> 
> with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
>    with DAG(name="d"):
>         for i in [1, 2, 3]:
>            echo_num(i).with_(name="my-echo")
> ```

I really like this idea but are you proposing for this syntax to create the `withItems` on the Argo side or just call it multiple times?

**Comment by elliotgunton** [comment]
Yes we would still use `with_items`, not multiple `Task`s. Basically by checking the current DAG's tasks and if the current task has the same name then "assume" the user wants to use `with_items` and move the argument into that list

**Comment by dejamiko** [comment]
Hmm, not sure if this is the best idea. I think this is too strong of an assumption to make. What if we have some specific order and use outputs of one of the calls?

```python
@script(directly_callable=True)
def echo_num(number: int = 42) -> Annotated[int, Parameter(name="number")]:
   print(number)
   return number


with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
   with DAG(name="d"):
      first = echo_num(1).with_(name="my-echo")
      # use results of first
      second = echo_num(first.results.whatever).with_(name="my-echo-2")
```

Would we collapse that into `with_items`?

Is it possible to inspect at runtime if we are inside a for loop? We can then only make that assumption for `Tasks` created in that context.

**Comment by elliotgunton** [comment]
>Would we collapse that into with_items?

No - there are two tasks with separate names

**Comment by dejamiko** [comment]
> > Would we collapse that into with_items?
> 
> No - there are two tasks with separate names

Ah, I see, the `name` of the `Task`, not just using the same `template`. That makes sense!

**Comment by elliotgunton** [comment]
There's a bit more to it actually. With these functions:

```py
@script(directly_callable=True)
def a_list() -> Annotated[List[int], Parameter(name="numbers")]:
   return [42, 0, 1]

@script(directly_callable=True)
def echo_num(number: int = 42) -> Annotated[int, Parameter(name="number")]:
   return number
```

Ideally we want to call `echo_num` with a `.result` from `a_list`, and have it understand that it's a list of ints to use, but we only get the list of ints at runtime. Hmm. The problem is from Argo, in that `result` could be a single value from a function like `echo_num`, or a list of values from `a_list`. I'd say this falls on the programmer to make it clear what they want, and in this case you'd have to do `with_param` for the dynamically-generated list. For a single value, passing `.result` would work fine.

For `with_params`, we can either go for the empty kwargs call or disallow that usage (by raising an exception) and force an explicit `Task` usage:

```py
with Workflow(generate_name="script-default-params-", entrypoint="d") as w:
    with DAG(name="d"):
        get_list = a_list().with_(name="get-list")
        get_num = echo_num().with(name="get-num")
        # The following is allowed and normal syntax as at runtime `outputs.result` is substituted:
        echo_the_num = echo_num(get_num.result).with(name="echo-num")

        # Then we have a choice for structured `.result`s:
        # Option 1
        loop = echo_num().with_(name="echo-list", with_param=get_list .result)
        # Option 2
        loop = Task(name="echo-list", template=echo_num, with_param=get_list .result)
        get_list >> loop 
```

Looking at them side-by-side, the second is probably clearer.

In a dream world this would work (but remember we're trying to define the yaml here, so it won't ☹)
```py
for i in get_list.result:
    loop = echo_num(i).with_(name="echo-list")
```

**Comment by dejamiko** [comment]
If `with_param` and `with_items` cannot be combined with arguments, I think Option 2 is the clearest. This way, the user knows that we are bypassing the normal function call and `with_param` or `with_items` is the entity responsible for passing arguments.

**Comment by elliotgunton** [comment]
Superseded by HEP0001 - https://github.com/argoproj-labs/hera/milestone/3 - we won't be making future feature enhancements to the context manager syntax
