### ISSUE TITLE
Configurable duration suspend template

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#765]
**Is your feature request related to a problem? Please describe.**
When creating a suspend template using Hera's `Suspend` class, there is no way to set the duration according to an input parameter.

**Describe the solution you'd like**
An option to pass in the duration for the Suspend template. This could be adding the `IOMixin` to `Suspend`.

**Describe alternatives you've considered**
The functionality already exists when using the Argo models, see #764.

An alternative feature in the Hera class could be a boolean of `input_duration` where if true, an input parameter called `duration` is available to set when the template is called (however this is not very transparent).

**Comment by flaviuvadan** [comment]
> An option to pass in the duration for the Suspend template. This could be adding the IOMixin to Suspend.

Def support this @elliotgunton!
