### ISSUE TITLE
Hera does not prioritize user-specified arguments in fanouts

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#766]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [x] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [ ] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**

Fanouts with extra parameters in Python functions that are specified via `arguments` can result in duplicate parameter specifications in the arguments field.

**To Reproduce**
Full Hera code to reproduce the bug, taken from Hera example:
```py
from hera.workflows import DAG, Workflow, script


@script()
def generate():
    import json
    import sys

    json.dump([i for i in range(10)], sys.stdout)


@script()
def consume(value: int, param1: str, param2: int = 42):
    print(value, param1, param2)


with Workflow(generate_name="dynamic-fanout-", entrypoint="d") as w:
    with DAG(name="d"):
        g = generate()
        c = consume(
            with_param=g.result,
            arguments={
                "value": "{{item}}",
                "param1": "hello",
                "param2": 42,
            },
        )
        g >> c

w.create()
```

These are the arguments that are set:
![Screenshot 2023-09-04 at 7 38 58 PM](https://github.com/argoproj-labs/hera/assets/18152652/fcbe7f46-43c6-4011-86a0-5b20ba5edeb7)

**Expected behavior**
No duplicate arguments. Hera should assume the user knows what they are doing and prioritize taking the user specified arguments rather than infer the `{{item.param}}` for every param

**Comment by dejamiko** [comment]
I am surprised to see this bug, since there is code trying to avoid this https://github.com/argoproj-labs/hera/blob/0b7079bffea22a576b89f78a5f633709d464d939/src/hera/workflows/_mixins.py#L634C48-L634C48

**Comment by flaviuvadan** [comment]
@dejamiko very much agree, have not had the chance to debug but I was also certain this is already handled by Hera by exactly the code you pointed out
