### ISSUE TITLE
Add Node Tolerations/Affinity Support to Container

### ISSUE THREAD

**Issue by fazilhero** [argoproj-labs/hera#773]
**Is your feature request related to a problem? Please describe.**
I would like to specify the pod affinities and tolerations but I couldn't find a python wrapper around it in hera. How can I define this?

**Describe the solution you'd like**
Ability to pass node tolerations

**Comment by flaviuvadan** [comment]
Hey @fazilhero! You can definitely set affinity and tolerations on [containers](https://hera.readthedocs.io/en/stable/api/workflows/hera/#hera.workflows.Container). The `Container` implementation [inherits](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/container.py#L29) from the `Template`, which allows you to set [affinity](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/_mixins.py#L422) and [tolerations](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/_mixins.py#L448).

```python
from hera.workflows import Container, models as m

c = Container(affinity=m.Affinity(...), tolerations=[m.Toleration(...)])
```


@elliotgunton and @samj1912 I wonder if we can make `mkdocs` display the inherited fields on child classes as well, which would make this more clear in the docs + not require users to understand the inheritance chain of Hera objects?

**Comment by fazilhero** [comment]
Yeah, i didn't know if we're supposed to use the models as they look like 1to1 argo mapping. Perhaps some doc can clear as I wasn't sure how to do the hera way

**Comment by elliotgunton** [comment]
@flaviuvadan created new issue #774 from your comment! Very good idea 💯 Closing this issue as the initial question was answered
