### ISSUE TITLE
Make properties of Hera classes more discoverable

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#774]
> Hey @fazilhero! You can definitely set affinity and tolerations on [containers](https://hera.readthedocs.io/en/stable/api/workflows/hera/#hera.workflows.Container). The `Container` implementation [inherits](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/container.py#L29) from the `Template`, which allows you to set [affinity](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/_mixins.py#L422) and [tolerations](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/_mixins.py#L448).

```python
from hera.workflows import Container, models as m

c = Container(affinity=m.Affinity(...), tolerations=[m.Toleration(...)])
```

> @elliotgunton and @samj1912 I wonder if we can make `mkdocs` display the inherited fields on child classes as well, which would make this more clear in the docs + not require users to understand the inheritance chain of Hera objects?

_Originally posted by @flaviuvadan in https://github.com/argoproj-labs/hera/issues/773#issuecomment-1712570411_

**Comment by lessthantrue** [comment]
Would it be less work in the long term to instead use the [native python kubernetes model](https://github.com/kubernetes-client/python/tree/master/kubernetes/client/models)? Maybe a good idea for a later ticket.
