### ISSUE TITLE
Validation error when using Stored Template but job works fine

### ISSUE THREAD

**Issue by vikramsg** [argoproj-labs/hera#784]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [ ] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
_A clear and concise description of what the bug is:_

_Error log if applicable_:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vikramsg/Projects/pipeline/hera_sr.py", line 299, in <module>
    create_workflow()
  File "/home/vikramsg/Projects/pipeline/hera_sr.py", line 295, in create_workflow
    w.create()
  File "/home/vikramsg/Projects/pipeline/pipe-src/.venv/lib/python3.8/site-packages/hera/workflows/workflow.py", line 385, in create
    wf = self.workflows_service.create_workflow(
  File "/home/vikramsg/Projects/pipeline/pipe-src/.venv/lib/python3.8/site-packages/hera/workflows/service.py", line 847, in create_workflow
    return Workflow(**resp.json())
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Workflow
status -> storedTemplates -> namespaced/s3-copy-templates-v6/copy-processing-data -> container -> imagePullPolicy
  value is not a valid enumeration member; permitted: 'Always', 'IfNotPresent', 'Never' (type=type_error.enum; enum_values=[<ImagePullPolicy.always: 'Always'>, <ImagePullPolicy.if_not_present: 'IfNotPresent'>, <ImagePullPolicy.never: 'Never'>])

```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
def _s3_download_processing_data() -> Step:
    return Step(
        name="s3-download-processing-data",
        template_ref=m.TemplateRef(
            name="s3-copy-templates-v6",
            template="copy-processing-data",
        ),
    )
```

**Environment**
 - OS: [Kubuntu]
 - Browser: [firefox]
 - Version of Hera: [5.7.1]
 - Version of Argo: [3.4.4]

**Additional context**
I am trying to submit a job using Hera that references a stored template on Argo. The issue is that Hera seems to complain while linting. Remarkably, the job still submits fine, and right now seems to work as intended. 

It is pretty difficult to debug however, since the problem occurs at `Workflow(**resp.json())` which is a huge `json` argument. I am assuming it is ingesting the template and validating it, but finds an issue with it?

Anyway to fix this? Alternatively, anyway to debug this to get to why this is happening?

**Comment by flaviuvadan** [comment]
Hey @vikramsg! Thanks for reporting this. I will take a look. [I think it has to do with how that field is mapped](https://github.com/argoproj-labs/hera/blob/main/src/hera/workflows/workflow.py#L170). Will report back

**Comment by flaviuvadan** [comment]
To confirm, your workflows are created successfully but the response is not handled properly?

**Comment by vikramsg** [comment]
Hi @flaviuvadan ,

Thanks for having a look. Yes, the workflow is created and runs on Argo exactly like it should but I get the error as a response when launching it.

**Comment by flaviuvadan** [comment]
@vikramsg do you happen to know what the response is from the server? 
```
  value is not a valid enumeration member; permitted: 'Always', 'IfNotPresent', 'Never' (type=type_error.enum; enum_values=[<ImagePullPolicy.always: 'Always'>, <ImagePullPolicy.if_not_present: 'IfNotPresent'>, <ImagePullPolicy.never: 'Never'>])
```
What is the value of `value` in this log?

**Comment by flaviuvadan** [comment]
@vikramsg I think this has to do with the mismatch between enum and the proper string.. I think I know how to solve it, I will open a PR and tag you
