### ISSUE TITLE
`global_config` has to be present in every script that has a `RunnerScriptConstructor`

### ISSUE THREAD

**Issue by vikramsg** [argoproj-labs/hera#854]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [x] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [x] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
When using the `RunnerScriptConstructor` I always need to put `global_config.image` in the script that has an `@script`. This is counter-intuitive, since we are using something called `global_config`. I would prefer to put all global configurations in one place rather than repeating them in every script. 

The same is of course true with things like `global_config.set_class_defaults(Script, constructor="runner")`. They always have to be in the script where a function with the `@script` is defined.

**Comment by flaviuvadan** [comment]
@vikramsg let's say you wrote the global config in file `x.py` and the script in `y.py`. Does `y.py` import `x.py`? I think that might be the issue, that nothing _runs_ the global config. If you have any internal __init__ file, let's say `my_org`, then you could place the config in there to make it truly global. 

For example, this should work:

```python
my_pkg
    __init__.py 
        global_config.image = "test:latest"
   other_module.py
```

```
from my_pkg import other_module
from hera import script, workflow

@script
def foo()...
   other_module.foo()

with Workflow() as w
    with DAG()
        foo()

w.create()
```

**Comment by vikramsg** [comment]
> Does y.py import x.py?

Yes it does. But I will try out your suggestion as well.
