### ISSUE TITLE
Improve Hera I/O models

### ISSUE THREAD

**Issue by samj1912** [argoproj-labs/hera#858]
**Is your feature request related to a problem? Please describe.**

Currently hera i/o with annotated params can become extremely verbose. The output syntax is especially error-prone.

**Describe the solution you'd like**

Introduce a HeraInput and HeraOutput class which derives from pydantic basemodel. When this is present, hera script runner will expand out the top level class attributes to params.

```python
from hera.workflows.io import Input, Output


class AnotherModel(BaseModel):
	...

class MyInput(InputModel):
	my_param: int = 1
	another_param: Annotated[int, Parameter(name="another-param") = 2
	another_artifact: Annotated[AnotherModel, Artifact(...)]


class MyOutput(OutputModel):
	my_output: str = ""
	another_output: Annotated[Path, Parameter("test"]]

def my_function(my_input: MyInput, another_param_inline: int) -> MyOutput:
	...
	outputs = MyOutput(exit_code=10)
	outputs.my_output = "foo"
	outputs.another_output.write("foo")
	outputs.result = "foo"
	return outputs
```

**Describe alternatives you've considered**

**Additional context**

**Comment by elliotgunton** [comment]
Released in 5.14.0
