### ISSUE TITLE
Improve example directory structure to accommodate complex "mini projects"

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#883]

**Comment by paravatha** [comment]
@flaviuvadan great idea!
I am thinking of contributing examples for ML project use-cases, start with something like an example pipeline using spaCy or PyTorch

**Comment by flaviuvadan** [comment]
That would be amazing @paravatha!

**Comment by elliotgunton** [comment]
@paravatha feel free to add a folder with your example code under `examples/workflows/use-cases` [here](https://github.com/argoproj-labs/hera/tree/ec7e5edb7e386902b4c889cd89f28fffb190cd11/examples/workflows/use-cases), though we'll need to see how you structure it to be able to add it to the docs website automatically (which won't happen right now).

**Comment by paravatha** [comment]
@flaviuvadan @elliotgunton Thanks. I like the new folder structure. 
Will try few things this weekend
