### ISSUE TITLE
Remove the need to write `.value` on `Parameter`s passed to `arguments`

### ISSUE THREAD

**Issue by flaviuvadan** [argoproj-labs/hera#923]
**Is your feature request related to a problem? Please describe.**
If users don't write `.value` on `arguments={'a': other.get_parameter('a').value}` then Hera passes a Pydantic dictionary representation of the `a` parameter object. So, the problem is that the code works syntactically but it breaks semantically

**Describe the solution you'd like**
Hera automatically performs `.value` internally if any object passed to the `arguments` mapping is a `Parameter`

CC: @ljyanesm

**Comment by elliotgunton** [comment]
This would be a simple `isinstance(v, Parameter)` before creating another parameter from the value here https://github.com/argoproj-labs/hera/blob/6979d06943c65427e3159668b5304a5fa9dc7c4e/src/hera/workflows/_mixins.py#L342
