### ISSUE TITLE
RunnerInput: Got 400 from Argo, a value was not supplied in the parameter

### ISSUE THREAD

**Issue by sam2x** [argoproj-labs/hera#961]
Hello,

Thank you for this framework. I am facing an issue using "RunnerInput" with typical inputs i would like to structure.

### Issue 
The code is as below:
```python
class DefaultParamsModel(BaseModel):
   name: str = "default value"
   my_var: str = "another default str"

class MyDefaultInput (RunnerInput):
    my_env: Annotated[DefaultParamsModel, Parameter(name="scope")] = DefaultParamsModel(
        name="test",
        my_var="bla",
    )
    stdout: Annotated[Path, Parameter(global_name="stdout", name="stdout", output=True)]
    stderr: Annotated[Path, Parameter(global_name="stderr", name="stderr", output=True)]

[...]

@script(constructor="runner") 
def ctn_test(my_input: MyDefaultInput) -> MyDefaultOutput: 
   [my_code...]
   return MyDefaultOutput(exit_code=exit_code, result="???", stdout=my_stdout, stderr=my_stderr,...)
```

I would like to use the statement below mentioned in the documentation:

> Input-Output function parameters
Hera also allows output Parameter/Artifacts as part of the function signature when specified as a Path type, allowing users to write to the path as an output, without needing an explicit return. They require an additional field output=True to distinguish them from the input parameters and must have an underlying Path type (or another type that will write to disk).

I want to use annotation feature so I don't have to duplicate the declaration. In my context, the goal is to use a variable referenced in "inputs" (as parameter, so without having to create a "temporary" file), fill the content during execution, record it as artefact, and after the exit to be available to others tasks (as well as others output). 

1. How to use it with the RunnerInput class ? 
2. If i use an artifact declaration in the function signature, will it be recorded automatically in my registered hera s3 despite the fact that here I declare it as "Parameter" (throught the "stdout" variable, and it is not "written" by myself on the fs) ? 
3. Is it possible to inherit from an existing RunnerInput class to add extra field in a new class ? so I don't have to rewrite all the arguments, trying to do something like that (based on the sample above): 
```python
MySecondDefaultInput(MyDefaultInput): 
    new_var: Annotated[Path, Parameter(name="...", output=True)]
```
4. It's still unclear for me the purpose of "result" with "RunnerOutput". In which use-case I would use it ?  

### Additional information
I am using latest version, I have embedeed the python lib to be run on the image. All works fine for this side. However for the declaration, I am not sure what i am doing wrong here. 
Notes :
- Expiremental Pydantic is enabled
- Experimental Annotations is enabled
- Latest version (5.14.0) is used

Thank you for any helps/pointers.

**Comment by elliotgunton** [comment]
Hi @sam2x - thank you for the feedback on this new feature! I will answer your questions numbered 1-4:

1. Currently, the use of `output=True` is not explicitly supported by the `RunnerInput` class (and I haven't tested it). You would need to workaround Pydantic's validation by setting a default value. I think it might work this way, but no guarantees!
```py
class MyDefaultInput (RunnerInput):
    stdout: Annotated[Path, Parameter(global_name="stdout", name="stdout", output=True)] = Path("/tmp/stdout.txt")
```
2. I think the answer is "no" but I'm not exactly clear on what you're asking - "If i use an artifact declaration in the function signature" vs "here I declare it as "Parameter" - you can only declare it as one or the other? Hera does different things for you automatically based on the type of function parameter, so you would have to use `S3Artifact` to "be recorded automatically".
3. Yes that should work - I can add a test to confirm it
4. The `result` is meant to emulate the script result (see [docs](https://argo-workflows.readthedocs.io/en/latest/walk-through/scripts-and-results/#scripts-and-results)) - to allow steps/dags to use the syntax of `{{steps.my-step.outputs.result}}`

**Comment by sam2x** [comment]
Hello @elliotgunton, thank you for the quick reply. I start to get more visibility on this.

1. This was also my outcome, the use of it doesnt seems yet supported under RunnerInput specific context usage.  
2. Just mixed my explanation. I thought this specific "output=True" would generate an "artifact" under the hood (since it provide a Path i would "write_text" to) without having to explicitely add it in the "outputs" arguments. 
3. Awesome
4. Oh, make sense now, thanks! 

Following my exploration, It seems that the RunnerInput documentation sample is not working out-the-box. I used the documentation example: 
``` python
class MyInput(RunnerInput):
    param_int: Annotated[int, Parameter(name="param-input")] = 42
    an_object: Annotated[MyObject, Parameter(name="obj-input")] = MyObject(
        a_dict={"my-key": "a-value"}, a_str="hello world!"
    )
    artifact_int: Annotated[int, Artifact(name="artifact-input", path="/tmp/test.txt", loader=ArtifactLoader.json)]

class MyOutput(RunnerOutput):
    param_int: Annotated[int, Parameter(name="param-output")] 
    artifact_int: Annotated[int, Artifact(name="artifact-output")]
    
@script(constructor="runner")
def pydantic_io(
    my_input: MyInput,
) -> MyOutput:
    return MyOutput(exit_code=1, result="Test!", param_int=42, artifact_int=my_input.param_int)
``` 
And in my workflow I tried several way to submit the _pydantic_io_ :


|   |   |   |   |   |
|---|---|---|---|---|
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |

**Comment by sam2x** [comment]
Hello @elliotgunton, thank you for the quick reply. I start to get more visibility on this.

1. This was also my outcome, the use of it doesnt seems yet supported under RunnerInput specific context usage.  
2. Just mixed my explanation. I thought this specific "output=True" would generate an "artifact" under the hood (since it provide a Path i would "write_text" to) without having to explicitely add it in the "outputs" arguments. 
3. Awesome
4. Oh, make sense now, thanks! 

Following my exploration, It seems that the RunnerInput documentation sample is not working out-the-box. I used the documentation example: 
``` python
class MyInput(RunnerInput):
    param_int: Annotated[int, Parameter(name="param-input")] = 42
    an_object: Annotated[MyObject, Parameter(name="obj-input")] = MyObject(
        a_dict={"my-key": "a-value"}, a_str="hello world!"
    )
    artifact_int: Annotated[int, Artifact(name="artifact-input", path="/tmp/test.txt", loader=ArtifactLoader.json)]

class MyOutput(RunnerOutput):
    param_int: Annotated[int, Parameter(name="param-output")] 
    artifact_int: Annotated[int, Artifact(name="artifact-output")]
    
@script(constructor="runner")
def pydantic_io(
    my_input: MyInput,
) -> MyOutput:
    return MyOutput(exit_code=1, result="Test!", param_int=42, artifact_int=my_input.param_int)
``` 
And in my workflow I tried several way to submit the _pydantic_io_ :

```
  t_pydantic = pydantic_io()
```
|Code   | Result  | Observation | 
|---|---|---|
|``pydantic_io()``  |  inputs.artifacts.artifact-input was not supplied` |  Legit, since there isn't default value and we haven't a value for artifact_int |
|``pydantic_io(arguments=MyInput())``   | ValidationError: 1 validation error for MyInput artifact_int field required (type=value_error.missing)  |  Legit validation error on missing 'artifact_int', which make sense so far for me   | 
|``pydantic_io(arguments=MyInput(artifact_int=0))``   | Parameter._check_name (parameter.py:29) ValueError: name cannot be `None` or empty when used  |  Exepcted, the way I pass value is wrong| 
|``pydantic_io(arguments={'my_input':MyInput(artifact_int=0)}) ``| BadRequest: Server returned status code 400 with message: `templates.main.tasks.pydantic-io templates.pydantic-io inputs.artifacts.artifact-input was not supplied`  |  I was hoping this one to work | 
   
Do you have by any chance:
1. A way to make this work ? 
2. An example how i would be able to "overwrite" a default parameter ? 

Thank you
