### ISSUE TITLE
Remove Python 3.8 support

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#969]
Python 3.8 is currently in security-fixes only, and reaches end of life later this year (2024-10) - we should drop support for 3.8, which will help clean up the repo.

## List of tasks:

- [x] Update pyproject.toml - remove 3.8 PyPi classifier, set python >=3.9, run `poetry lock`
- [x] Remove from cicd.yaml, use 3.9 in pre-release.yaml, publish.yml
- [x] Remove files added for backwards compat (unparse.py, graphlib.py, possibly some others)
- [x] Use 3.9 for generating test data (update Makefile target)
- [x] Use 3.9 for generating models using datamodel-codegen
- [x] Use 3.9 as default `global_config` image and regenerate examples

**Comment by flaviuvadan** [comment]
I think this will also close #584 as a "not fix" (unfortunately :( )

**Comment by jeongukjae** [comment]
one month left!
And also we can remove these branch codes.
https://github.com/argoproj-labs/hera/blob/ca9417683f824eb6eb038c6a14e7b6be7e11f048/src/hera/shared/_type_util.py#L6-L11

**Comment by samj1912** [comment]
I am more than happy to expedite the removal. I would be completely fine removing it now given how close it is to the end date.
