### ISSUE TITLE
Upgrade Argo >= 3.5

### ISSUE THREAD

**Issue by Sharathmk99** [argoproj-labs/hera#993]
**Is your feature request related to a problem? Please describe.**
It would be great to upgrade the Argo Models to >= 3.5 version as we need to use `pod_gc` with `deleteDelayDuration` field which exist only in >= 3.5 version.

**Describe the solution you'd like**
We wanted to leverage `deleteDelayDuration` feature in `pod_gc` which is available in >= 3.5 version.
Ref link - https://github.com/argoproj/argo-workflows/blob/main/examples/pod-gc-strategy-with-label-selector.yaml

**Describe alternatives you've considered**
Currently I don't have any alternative.

**Additional context**

**Comment by justinfx** [comment]
I was about to create a ticket when I ended up finding this open ticket. I too wanted to use "deleteDelayDuration" and found it wasn't part of the model yet.

**Comment by justinfx** [comment]
I think I misunderstood the nature of this issue. Do we need a new issue to update the `PodGC` model to support the "deleteDelayDuration" field?
https://github.com/argoproj-labs/hera/blob/5.15.0/src/hera/events/models/io/argoproj/workflow/v1alpha1.pyi#L521
