### ISSUE TITLE
Workflow parameter interpolation issue in WorkflowTemplates

### ISSUE THREAD

**Issue by tico24** [argoproj-labs/hera#995]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [x] exporting to YAML
- [x] submitting to Argo
- [ ] running on Argo with the Hera runner
- [ ] other: 

<h2>Bug report</h2>

**Describe the bug**
When trying to create a workflowTemplate that contains a parameter, if the parameter is empty (`""`), then the creation fails.

_Error log if applicable_:
```bash
Traceback (most recent call last):
  File "/example_wftemplate.py", line 38, in <module>
    example_wftemplate.create()
  File "/opt/homebrew/lib/python3.11/site-packages/hera/workflows/workflow_template.py", line 57, in create
    return self.workflows_service.create_workflow_template(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/hera/workflows/service.py", line 690, in create_workflow_template
    raise exception_from_server_response(resp)
hera.exceptions.BadRequest: Server returned status code 400 with message: `templates.main.tasks.deploy-resource-pod templates.deploy-resource-pod.resource.manifest must be a valid yaml`
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import *
from hera.shared import global_config
from hera.exceptions import AlreadyExists

global_config.host = "https://localhost:8443/argo/"
global_config.token = "unused"
global_config.verify_ssl = False
global_config.namespace = 'argo'

deploy_resource_manifest_pod = '''apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:{{workflow.parameters.container_tag}}
'''

deploy_resource_pod = Resource(name="deploy-resource-pod",
                            action="apply",
                            success_condition="status.phase == Running",
                            manifest=deploy_resource_manifest_pod
                            )

with WorkflowTemplate(
    name="poddy-pod",
    entrypoint="main",
    arguments=[
        Parameter(name="container_tag", value=""),
    ],
) as example_wftemplate:
    with DAG(name="main") as main:
        deploy_resources_pod = deploy_resource_pod(name="deploy-resource-pod")

example_wftemplate.to_file(".")
try:
    example_wftemplate.create()
except AlreadyExists:
    example_wftemplate.update()

```

If you set the following line to have a non-empty value, it will work:
```py
        Parameter(name="container_tag", value=""),
```

**Expected behavior**
I would expect to be able to create a workflowTemplate with empty workflowParameters for later population at runtime.

**Environment**
- Hera Version: 5.14.1
- Python Version: 3.11.7
- Argo Version: 3.5.5

**Additional context**

**Comment by Joibel** [comment]
As a note - the `to_file` version of the template is correctly rendered.

**Comment by elliotgunton** [comment]
This seems to be more-so a problem on Argo's side, especially if `to_file`/`to_yaml` looks correct. Setting a parameter on a `Workflow`'s arguments can't take defaults as it is supposed to be the real value to be used, and it seems that even for `WorkflowTemplate`s the value is replaced upon submission. I would suggest using an input parameter `container_tag` to your DAG, and then when you submit a `Workflow` you can set that argument. Then you would change
```
workflow.parameters.container_tag
```
to 
```
inputs.parameters.container_tag
```

Could you confirm this approach and whether the problem / feature enhancement is on Argo's side?

**Comment by tico24** [comment]
Yeh, I was about to write the same. It indeed as coming from argo's side :(

**Comment by tico24** [comment]
I'll close this issue. I don't believe this has anything to do with Hera. Thanks for your assistance.
